avalon/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^avalonol/', include('avalonol.urls',namespace='avalonol')),
    url(r'^admin/', admin.site.urls),
]

avalonol/urls.py
from django.conf.urls import url
from . import views

app_name = 'test2'
urlpatterns = [
    url(r'^login/$',views.login,name='login'),
    url(r'^hall/$',views.hall,name='hall'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^players/$',views.players,name='players'),
    url(r'^instance/$',views.instance,name='instance'),
    url(r'^game/$',views.game,name='game'),
    url(r'^message/$',views.message,name='message'),
    url(r'^stage/$',views.stage,name='stage'),
    url(r'^board/$',views.board,name='board'),
    url(r'^notice/$',views.notice,name='notice'),
    url(r'^chooseopen/$',views.chooseopen,name='chooseopen'),
    url(r'^choose/$',views.choose,name='choose'),
    url(r'^voteopen/$',views.voteopen,name='voteopen'),
    url(r'^vote/$',views.vote,name='vote'),
    url(r'^backtohall/$',views.backtohall,name='backtohall'),
    url(r'^test/$',views.test,name='test'),
    # url(r'^$', views.index, name = 'index'),
    # url(r'^(?P<grade_id>[0-9])/$',views.detail,name = 'detail'),
]

avalonol/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=16)
    displayname = models.CharField(max_length=16)

    class Meta:
        db_table = 'user'

avalonol/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.http import HttpResponseRedirect
from django.template import RequestContext

# import urllib.parse

from .models import User

from .helper import helper
from . import process

# Create your views here.
def login(request):
    if 'avalon_id' in request.session:
        user = User.objects.get(id = request.session['avalon_id'])
        return HttpResponseRedirect('/avalonol/hall/')
    else:
        if 'username' in request.POST:
            if len(User.objects.filter(username__exact=request.POST['username']))==1:
                user = User.objects.get(username=request.POST['username'])
                if user.password == request.POST['password']:
                    request.session['avalon_id'] = user.id
                    return HttpResponseRedirect('/avalonol/hall/')
                else:
                    return render(request,'avalonol/login.html',{'errormsg':'密码错误！'})
            else:
                return render(request,'avalonol/login.html',{'errormsg':'用户名错误！'})
        else:
            return render(request,'avalonol/login.html',{'errormsg':'请先登录！'})

def logout(request):
    if 'avalon_id' in request.session:
        try:
            helper.playerList.remove(User.objects.get(id=request.session['avalon_id']).displayname)
            helper.avalonIdList.remove(request.session['avalon_id'])
        except:
            pass
        del request.session['avalon_id']
    return HttpResponseRedirect('/avalonol/login/')

def hall(request):
    if 'avalon_id' in request.session:
        user = User.objects.get(id = request.session['avalon_id'])
        if user.displayname not in helper.playerList:
            helper.playerList.append(user.displayname)
            helper.avalonIdList.append(user.id)
        else:
            pass
        return render(request,'avalonol/hall.html',{'user':user,'playerList':helper.playerList,'length':len(helper.playerList),'allingame':0})
    else:
        return HttpResponseRedirect('/avalonol/login/')

def players(request):
    return render(request,'avalonol/players.html',{'playerList':helper.playerList,'length':len(helper.playerList)})

def instance(request):
    if request.GET['command'] == '1':
        helper.commandback = 1
        helper.gamer = helper.avalonIdList[:]  #最终游戏玩家id单
        helper.playerList = []          #
        helper.avalonIdList = []        #清空hall内等待玩家名单
        helper.polls[helper.roundnum] = {}
    return HttpResponse(helper.commandback)

def game(request):
    if 'avalon_id' in request.session:
        if request.session['avalon_id'] in helper.gamer:
            if request.session['avalon_id'] in helper.gamermap:
                message = '你回到了游戏中。'
            else:
                process.opening()   #玩家实例化（安排位置与身份）
                message = '欢迎来到阿瓦隆！'
            return render(request, 'avalonol/game.html', {'message':message, 'gamer':helper.gamermap[request.session['avalon_id']],'que':helper.gamerque})
        else:
            return HttpResponse("对不起，您不在游戏中。")
    else:
        return HttpResponseRedirect('/avalonol/login/')

def message(request):
    message = process.message(request.session['avalon_id'])
    if helper.stageindex[0] == 0:
        process.superstagechange()
    elif helper.stageindex[0] == 6:
        message = "英勇的亚瑟军即将面临最后的危险！"
    elif helper.stageindex[0] == 7:
        message = "刺客趁乱挣脱开亚瑟军，给"+helper.bekilled+"了致命一击！亚瑟军胜利了！！"
    elif helper.stageindex[0] == 8:
        if helper.missionfailnum == 3:
            message = "莫德雷德阵营胜利了！！！"
        elif helper.missionsuccessnum == 3:
            message = "刺客趁乱挣脱开亚瑟军，给"+helper.bekilled+"了致命一击！莫德雷德阵营胜利了！！"
        elif helper.votefailnum == 5:
            message = "莫德雷德阵营成功地搅乱了亚瑟军的计划，胜利！！"
    return HttpResponse(message)

def stage(request):
    stageinfo = [helper.stageindex[0],helper.superstages[helper.stageindex[0]],helper.stageindex[1],helper.substages[helper.stageindex[1]]]
    return JsonResponse(stageinfo, safe=False)

def board(request):
    board = process.board()
    if request.GET['over'] == '1':
        helper.release += 1
        if helper.release == len(helper.gamer):
            process.gameover()
    return render(request, 'avalonol/board.html',{'board':board,'winlose':helper.winlose})

def notice(request):
    if len(helper.notice) > helper.noticelen:
        return HttpResponse(helper.notice[-1])
    else:
        return HttpResponse('0')

def chooseopen(request):
    if helper.stageindex[1] == 0 and helper.stageindex[0] < 6 and helper.gamermap[request.session['avalon_id']].seat == str(helper.leaderseat):
        return HttpResponse(helper.headcount[str(len(helper.gamer))][helper.missionround-1])
    elif helper.stageindex[0] == 6 and helper.gamermap[request.session['avalon_id']].role == '刺客':
        return HttpResponse(1)
    else:
        return HttpResponse(0)

def choose(request):
    rawmembers = request.GET['members'].replace("=on","").split('&')
    helper.fortest = rawmembers
    members = []
    for e in rawmembers:
        pass
        # members.append(urllib.parse.unquote(e))
    if helper.stageindex[0] < 6:
        process.recordmember(members)
    elif helper.stageindex[0] == 6:
        process.assassinate(members[0])
    return HttpResponse(members[0])    #返回无意义

def voteopen(request):
    if helper.stageindex[1] == 1 and request.session['avalon_id'] not in helper.polls[helper.roundnum]:
        return HttpResponse('open')
    elif helper.stageindex[1] == 2 and User.objects.get(id=request.session['avalon_id']).displayname in helper.memberstodecide:
        if request.session['avalon_id'] not in helper.missions[helper.roundnum]:
            return HttpResponse('open')
        else:
            return HttpResponse('close')
    else:
        return HttpResponse('close')

def vote(request):
    if helper.stageindex[1] == 1:
        whichvote = process.counting(request.session['avalon_id'],request.GET['vote'])
    elif helper.stageindex[1] == 2:
        whichvote = process.mission(request.session['avalon_id'],request.GET['vote'])
    return HttpResponse("Nothing")    #返回无意义

def backtohall(request):
    return HttpResponseRedirect('/avalonol/hall/')

def test(request):
    ttt = request.GET['test']
    return HttpResponse(eval(ttt))

avalonol/templates/avalonol/board.html
 <table>
    <tr>
        <th rowspan="2" class="leader">队长</th>
        <!--<th rowspan="2">顺位</th>-->
        <th rowspan="2" class="boardname">玩家</th>
        <th colspan="2" class="missions">任务1</th>
        <th colspan="2" class="missions">任务2</th>
        <th colspan="2" class="missions">任务3</th>
        <th colspan="2" class="missions">任务4</th>
        <th colspan="2" class="missions">任务5</th>
    </tr>
    <tr>
        <th class="team">队员</th><th class="vote">投票</th>
        <th class="team">队员</th><th class="vote">投票</th>
        <th class="team">队员</th><th class="vote">投票</th>
        <th class="team">队员</th><th class="vote">投票</th>
        <th class="team">队员</th><th class="vote">投票</th>
    </tr>
    {% for seat,indivboard in board.items %}
        <tr class="line">
            <td class="leaders">
                {% if indivboard.Leader != ''%}<img src={{ indivboard.Leader }} alt="★"/>
                {% else %}
                {% endif %}
            </td>
            <!--<td>{{ indivboard.Seat }}</td>-->
            <td class="boardnames">{{ indivboard.Name }}</td>
            {% for p in indivboard.Rounds %}
                <td class="team">
                    {% if p.0 == '1' %}<img src="/static/png/team_token.png"/>
                    {% else %}
                    {% endif %}
                </td>
                <td class="vote">
                    {% if p.1 == '0'%}<img src="/static/png/vote_reject.png"/>
                    {% else %}
                    {% endif %}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    <tr>
        <th colspan="2" class="result">任务结果</th>
        {% for result in winlose %}
            <td colspan="2" class="winlose">
                {% if result == 'W' %}<img src="/static/png/score_maker_ps.png"/>
                {% elif result == '1' %}<img src="/static/png/score_maker_2_ps.png"/>
                {% elif result == '2' %}<img src="/static/png/score_maker_2_ps.png"/><img src="/static/png/score_maker_2_ps.png"/>
                {% elif result == '3' %}<img src="/static/png/score_maker_2_ps.png"/><img src="/static/png/score_maker_2_ps.png"/><img src="/static/png/score_maker_2_ps.png"/>
                {% elif result == '4' %}<img src="/static/png/score_maker_2_ps.png"/><img src="/static/png/score_maker_2_ps.png"/><img src="/static/png/score_maker_2_ps.png"/><img src="/static/png/score_maker_2_ps.png"/>
                {% else %}
                {% endif %}
            </td>
        {% endfor %}
    </tr>
</table>

avalonol/templates/avalonol/game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="/static/game.css" rel="stylesheet" type="text/css"/>
    <script src="/static/jquery-1.11.3.min.js"></script>

    <script type="text/javascript">
        function main(){     //document.ready主体函数
            $.ajaxSetup({cache:false});
            stageupdate = self.setInterval("stageinfo()",500);
            process = self.setInterval("processcontrol()",500);
        }

        function stageinfo(){     //获取后台stageindex
            $.getJSON("{% url 'avalonol:stage' %}",function(stageinfo){
                $("#stageindex").val(stageinfo[0]);
                $("#stage").html(stageinfo[1]);
                $("#substageindex").val(stageinfo[2]);
                $("#substage").html(stageinfo[3]);
            });
        }

        function processcontrol(){
            var stageindex = $("#stageindex").val();
            var substageindex = $("#substageindex").val();
            var silast = $("#silast").val();
            var ssilast = $("#ssilast").val();
            if (stageindex+substageindex == silast+ssilast){
                return;
            }
            else{
                switch (Number(stageindex)){
                    case 0:
                        message();
                        board();
                        break;
                    case 6:
                        board();
                        message();
                        chooseopen();
                        voteopen();
                        break;
                    case 7:
                        clearInterval(process);
                        clearInterval(stageupdate);
                        board(1);
                        message();
                        $("#gameover").show();
                        break;
                    case 8:
                        clearInterval(process);
                        clearInterval(stageupdate);
                        board(1);
                        message();
                        $("#gameover").show();
                        break;
                    default:
                        switch (Number(substageindex)){
                            case 0:
                                notice();
                                board();
                                chooseopen();
                                break;
                            case 1:
                                board();
                                voteopen();
                                break;
                            case 2:
                                board();
                                voteopen();
                                break;
                        }
                }
                $("#silast").val(stageindex);
                $("#ssilast").val(substageindex);
            }
        }

        function message(){    //更新消息
            $.get("{% url 'avalonol:message' %}",function(msg){
                $("#msg").append("<p>"+msg+"</p>");
            });
        }

        function notice(){
            $.get("{% url 'avalonol:notice' %}",function(ntc){
                if (ntc != '0'){
                    $("#msg").append("<p>"+ntc+"</p>");
                }
            });
        }
        function board(){    //更新游戏面板
            var over = arguments[0]?arguments[0]:0;
            $.get("{% url 'avalonol:board' %}",{'over':over},function(boa){
                $("#board").html(boa);
            });
        }

        function chooseopen(){    //选择成员触发事件
            $.get("{% url 'avalonol:chooseopen' %}",function(chop){
                if(chop>0){
                    if ($("#stageindex").val() != '6'){
                        $("#member p").html("请在发言后选择队员");
                    }
                    else{
                        $("#member p").html("请与同伙们商量后刺杀");
                    }
                    $("#choose input").attr("disabled",false);
                    $("#headcount").val(chop);
                }
            });
        }

        function choose(){
            var inp = $("#choose input");
            var members = $("#choose input:checked").serialize();
            $("#choose input").attr("disabled",true);
            var headcount = 0;
            for (i=0;i<inp.length;i++){
                if(inp[i].checked){
                    headcount += 1;
                }
            }
            if (headcount == $("#headcount").val()){
                $.get("{% url 'avalonol:choose' %}",{'members':members},function(cho){
                });
            }
            else{
                alert("你必须选择"+$("#headcount").val()+"个成员，请重新选择！");
                $("#choose input").attr("disabled",false);
            }
        }

        function voteopen(){    //投票触发事件
            $.get("{% url 'avalonol:voteopen' %}",function(yoop){
                if(yoop=='open'){
                    $("#vote input").attr("disabled",false);
                    if ($("#substageindex").val() == '1'){
                        $("#votation p").html("请对队长的带队方案投票");
		        $("#no").val("反对");
			$("#yes").val("同意");
                    }
                    else{
                        $("#votation p").html("请选择执行/破坏任务卡");
                        $("#no").val("破坏任务");
                        $("#yes").val("执行任务");
                    }
                }
                else{
                    $("#vote input").attr("disabled",true);
                }
            });
        }

        function vote(yorn){
            $.get("{% url 'avalonol:vote' %}",{'vote':yorn},function(vot){
            });
            $("#vote input").attr("disabled",true);
        }

        function backtohall(){
            window.location.href="{% url 'avalonol:backtohall' %}";
        }

        function test(){
            var ttt = $("#testinput").val();
            $.get("{% url 'avalonol:test' %}",{'test':ttt},function(testresualt){
                alert(testresualt);
            });
        }

        function replace(){
            document.body.style.height = document.documentElement.clientHeight+"px";
            document.body.style.width = document.documentElement.clientWidth+"px";
        }
    </script>
    <script type="text/javascript">
        $(document).ready(main());
        window.onload = replace;
    </script>
</head>
<body>
    <div id="stageinfo">
        <p><span>游戏进程：</span><span id="stage"></span><span>-</span><span id="substage"></span></p>
    </div>
    <div id="msg">
        <p>{{ message }}</p>
        <p>你的角色是【{{ gamer.role }}】</p>
    </div>
    <div id="board">
        <table>
            <tr>
                <th rowspan="2" class="leader">队长</th>
                <!--<th rowspan="2">顺位</th>-->
                <th rowspan="2" class="boardname">玩家</th>
                <th colspan="2" class="missions">任务1</th>
                <th colspan="2" class="missions">任务2</th>
                <th colspan="2" class="missions">任务3</th>
                <th colspan="2" class="missions">任务4</th>
                <th colspan="2" class="missions">任务5</th>
            </tr>
            <tr>
                <th class="team">队员</th><th class="vote">投票</th>
                <th class="team">队员</th><th class="vote">投票</th>
                <th class="team">队员</th><th class="vote">投票</th>
                <th class="team">队员</th><th class="vote">投票</th>
                <th class="team">队员</th><th class="vote">投票</th>
            </tr>
            {% for seat,name in que.items %}
                <tr class="line">
                    <td class="leaders"></td>
                    <!--<td>{{ seat }}</td>-->
                    <td class="boardnames">{{ name }}</td><!--same with "player-->
                </tr>
            {% endfor %}
            <tr>
                <th colspan="2" class="result">任务结果</th>
            </tr>
        </table>
    </div>
    <div id="member">
        <p>请在发言后选择队员：</p>
        <form id="choose">
            {% for seat,name in que.items %}
                <input type="checkbox" class="checkbox" name="{{ name }}" disabled="disabled"/>{{ name }}
            {% endfor %}
            <input type="button" class="button" value="确定" onclick="choose()" disabled="disabled"/>
            <input id="headcount" type="hidden" value=""/>
        </form>
    </div>
    <div id="votation">
        <p>请对队长的带队方案投票：</p>
        <form id="vote">
            <input id="no" class="button" type="button" value="反对" onclick="vote(0)" disabled="disabled">
            <input id="yes" class="button" type="button" value="同意" onclick="vote(1)" disabled="disabled">
        </form>
    </div>
    <div id="gameover">
        <p></p>
        <input class="button" type="button" value="返回大厅" onclick="backtohall()"/>
    </div>
    <div id="test">
        <input id="testinput" type="text" name="test" />
        <input type="button" value="test" onclick="test()" />
        <input type="hidden" id="stageindex" value="0"/>
        <input type="hidden" id="substageindex" value="0"/>
        <input type="hidden" id="silast" value="9"/>
        <input type="hidden" id="ssilast" value="9"/>
    </div>
</body>
</html>

avalonol/templates/avalonol/hall.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="/static/hall.css" rel="stylesheet" type="text/css"/>
    <script src="/static/jquery-1.11.3.min.js"></script>

    <script type = "text/javascript">
        $(document).ready(setInterval(function(){
            $.ajaxSetup({cache:false})
            leaderStart();
            $.get("{% url 'avalonol:players' %}",function(ret){ //显示列表
                $("#players").html(ret);
                var playernum = $("#length").val();
                if (playernum >= 5 && playernum <= 10){
{#                if (playernum >= 1 && playernum <=10){#}
                    var indivname = $("#indivname").val();
                    var playerListFirst = $("#playerListFifth").val();
                    if (indivname == playerListFirst){
{#                    if (indivname == 'gallon'){#}
                        document.getElementById("startButton").style.display = 'block';
                    }
                }else{
                    document.getElementById("startButton").style.display = 'none';
                }
            });
{#            $.ajax({#}
{#                type: "get",#}
{#                url: "{% url 'avalonol:player' %}",#}
{#                ifModified: true,#}
{#                success: function(ccc){#}
{#                    alert(ccc);#}
{#                    $("#players").html(ccc);#}
{#                },#}
{#            });#}
        },3000));
    </script>
    <script type="text/javascript">
        function leaderStart(){  //触发leader开始事件
            var command = arguments[0]?arguments[0]:0;
            $.get("{% url 'avalonol:instance' %}",{'command':command},function(commandback){
                if (commandback == 1){
                    window.location.href="{% url 'avalonol:game' %}";
                }
            });
        }

        function replace(){
	    document.body.style.height = document.documentElement.clientHeight+"px";
	    document.body.style.width = document.documentElement.clientWidth+"px";
	}
    </script>
    <script type="text/javascript">
	window.onload = replace;
    </script>
</head>

<body>
    <div id="welcome">
        <p>登录成功！{{ user.displayname }} ～</p>
    </div>
    <div id="players">
        <p>现在共有{{ length }}位玩家在线！</p>
        <ul>
            {% for playerName in playerList %}
                <li>{{ playerName }}</li>
            {% endfor %}
            <input type="hidden" id="length" value="{{ length }}"/>
        </ul>
    </div>
    <div id="logout"><a href="{% url 'avalonol:logout' %}">退出登录</a></div>

    <div id="startButton" style="display:none;"><input type="button" value="开始游戏" onclick="leaderStart(1)"/></div>
    <span id="test" style="display: none;"></span>

    <input type="hidden" id="indivname" value="{{ user.displayname }}"/>
    <input type="hidden" id="playerListFifth" value="{{ playerList.4 }}"/>
</body>
</html>

avalonol/templates/avalonol/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link href="/static/login.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript">
        function replace(){
    	    document.body.style.height = document.documentElement.clientHeight+"px";
	    document.body.style.width = document.documentElement.clientWidth+"px";
	}
    </script>
    <script type="text/javascript">
        window.onload = replace;
    </script>
</head>
<body>
    <div id="errormsg"><p>{{ errormsg }}</p></div>
    <div id="login">
	<p>AVALON</p>
        <form action="{% url 'avalonol:login' %}" method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="请输入用户名"/><br>
            <input type="password" name="password" placeholder="请输入密码"/><br>
            <input class='button' type="submit" value="提交"/>
        </form>
    </div>
</body>
</html>

avalonol/templates/avalonol/players.html
<p>现在共有{{ length }}位玩家在线！</p>
<ul>
    {% for playername in playerList %}
        <li>{{ playername }}</li>
    {% endfor %}
</ul>
<input type="hidden" id="length" value="{{ length }}"/>